export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

//Tickets
export const LOAD_TICKETS_SUCCESS = 'LOAD_TICKETS_SUCCESS';
export const UPDATE_TICKET_SUCCESS = 'UPDATE_TICKET_SUCCESS';
export const CREATE_TICKET_SUCCESS = 'CREATE_TICKET_SUCCESS';
export const LOAD_PICKUPS_SUCCESS = 'LOAD_PICKUPS_SUCCESS';
//Integrations
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';

//Auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const INIT_AUTH_STATE = 'INIT_AUTH_STATE';

//User List
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';